apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: IMAGE_PLACEHOLDER
        # image: ahmedkamal200427400/team4:3
        volumeMounts:
        - mountPath: /app/instance
          name: my-volume
      volumes:
      - name: my-volume
        persistentVolumeClaim:
          claimName: ebs-sc-pvc
